authors:
  rushikesh:
    name: Rushikesh Deshmukh
    description: A passionate Infrastructure as Code enthusiast and blogger.
    avatar: https://avatars.githubusercontent.com/rushideshmukh-tech
    url: https://github.com/rushideshmukh-tech
